### ISSUE TITLE
which port i should use

### ISSUE THREAD

**Issue by simonchan2013** [wdavidw/node-hbase#26]
excuse me, i have no idea about hbase({ host: '127.0.0.1', port: 8080 }), i want to know which port i should use,,the Master port? or HBase Master web port, or others. wish your answer, thanks

**Comment by wdavidw** [comment]
You must start the rest server as a separate process from the masters and regionservers and use its port

**Comment by simonchan2013** [comment]
great~~now i can visit hbase~thanks a lot

**Comment by simonchan2013** [comment]
another problem occurs, your samples in github and in the doc use getRow method, but when i try it, it will response the error message like this:
TypeError: Object [object Object] has no method 'getRow'
    at Object.<anonymous> (E:\work\workspace_js\nodejs_test\public_module\hbaseTest.js:10:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

and i search all your code in the node_module folder of my project, i can't find the getRow method in    any js file, is it I should add other source into my project? wait for your answer~thanks~

**Comment by wdavidw** [comment]
It is now renamed "row". I've updated the doc. Look at the tests if you need inspiration, I never push on github unless they all pass.
