### ISSUE TITLE
can I get multi rows in one request

### ISSUE THREAD

**Issue by simonchan2013** [wdavidw/node-hbase#27]
excuse me, if I want to get all rows which row_key like "a_xxx"(such as a_001, a_002, a_100,...), how can I get all of these rows with one request? thanks

**Comment by wdavidw** [comment]
You need to set up a filter, probably based on a regex. Look at [those tests](https://github.com/wdavidw/node-hbase/blob/master/test/filter.coffee#L25-L26)
