### ISSUE TITLE
Google Cloud BigTable

### ISSUE THREAD

**Issue by ashleybrener** [wdavidw/node-hbase#28]
Is `node-hbase` suitable for [Cloud BigTable](https://cloud.google.com/bigtable)?

If so does it communicate with the [Cloud BigTable HBase Client](https://cloud.google.com/bigtable/docs/installing-hbase-client) (Java).
As it reads on the BigTable website "*The Cloud Bigtable HBase client enables your application to connect to Cloud Bigtable through the Apache HBase API.*"

If so, is there a (recommended) way to bypass such a client and connect directly to the DB with `node-hbase`.

Thanks.

**Comment by wdavidw** [comment]
I'm not familiar with the BigTable API. This module communicate with the HBast REST server (aka stargate), check if BigTable provide a compatible HTTP/REST interface (and let me know if this is the case, i'll update the documentation in such a case)

**Comment by zrosenbauer** [comment]
Was this ever confirmed? I have this listed on my "awesome-bigtable" list... but wanted to confirm (I just removed it but can add back)
