### ISSUE TITLE
docs -> scanner.md is broken

### ISSUE THREAD

**Issue by adamkleingit** [wdavidw/node-hbase#33]
looks like a ``` is missing or there's an extra one.
File:
https://github.com/wdavidw/node-hbase/blob/5f60ee620a17748f820d5f6b42200a03ee812eef/doc/scanner.md

**Comment by wdavidw** [comment]
i've removed the docs folder which was outdated. At the same time, i've converted source code to literate coffee (markdown), [eg scanner](https://github.com/wdavidw/node-hbase/blob/master/src/scanner.coffee.md)
