### ISSUE TITLE
why rows.length=1000 when when I scan a table with a record of more than 1000

### ISSUE THREAD

**Issue by sunsummit** [wdavidw/node-hbase#42]
Hello,first thank you answer my last quertion.Now I have another question,in use scan method,I set:
      filter:
      {
        "value":2000,"type":"PageFilter"
      },
and my table have 5000 records,In callback function of scan,I get rows.length=1000,why?
thanks!

**Comment by wdavidw** [comment]
did u try a lower limit like 100? maybe u hit a server side setting, dont know. be carefull, not all filters were implemeted into the rest api at the time i wrote this library so maybe u'll have to add this functionnality yourself and send me a pull request
