### ISSUE TITLE
Use startTime and endTime

### ISSUE THREAD

**Issue by JoaoPauloFP** [wdavidw/node-hbase#44]
Hello, I'm trying filter only rows between 1470937869725 and 1470937869735 timestamp.

var hbase = require('hbase');
var client = new hbase.Client({host: '127.0.0.1', port: 8080});
var myScanner = client.table('MyTable').scan({startTime: 1470937869725, endTime: 1470937869735}, function(err, rows){
            console.log(rows);
        });

But all events are retrieved (not just those in the interval).

What am I doing wrong?

**Comment by wdavidw** [comment]
It seems right. You can get inspiration from the [scan test](https://github.com/wdavidw/node-hbase/blob/master/test/filter.coffee)
