### ISSUE TITLE
NPM install failing due to krb5@0.1.0

### ISSUE THREAD

**Issue by Lutziferbox** [wdavidw/node-hbase#48]
Since the bumb from hbase@0.2.2 to hbase@0.2.3, the npm install is failing due to the change from krb5@0.0.3 to krb5@0.1.0.

The exact error message is "fatal error C1083: Cannot open include file: 'gssapi.h': No such file or directory (compiling source file ..\src\krb5.cc)". I tried installing the complete visual studio compile chain, python2.7 and even MIT Kerberos, but the error remains the same.
"npm install hbase@0.2.3 --no-optional" is working fine, but since i cannot specify the "--no-optional" in the package.json, this will not suffice.

**Comment by wdavidw** [comment]
You shall redirect this message to the krb5 project with more detailed information. It works for me on my dev environment.

**Comment by wdavidw** [comment]
Could you please take the time to report an issue on the [krb5] project. We'll be happy to fix it but we need additionnal information like your OS.

**Comment by Lutziferbox** [comment]
Actually, I cannot find a way to do so. There is no way to submit issues to github.com/krb5/krb5 or www.npmjs.com/package/krb5.
My OS is Windows 10 and my node version is 6.9.1.
I tried to set up the whole windows toolchain for nody-gyp but it did not resolve the issue:


...\node_modules\krb5\src\krb5.h(5): fatal error C1083: Cannot open includ e file: 'gssapi.h': No such file or directory (compiling source file ..\src\krb5.cc) [...\node_modules\krb5\build\krb5.vcxproj]
...\node_modules\krb5\src\krb5.h(5): fatal error C1083: Cannot open includ e file: 'gssapi.h': No such file or directory (compiling source file ..\src\worker.cc) [...\node_modules\krb5\build\krb5.vcxproj]
...\node_modules\krb5\src\krb5.h(5): fatal error C1083: Cannot open includ e file: 'gssapi.h': No such file or directory (compiling source file ..\src\addon.cc) [...\node_modules\krb5\build\krb5.vcxproj]
...\node_modules\krb5\src\krb5.h(5): fatal error C1083: Cannot open includ e file: 'gssapi.h': No such file or directory (compiling source file ..\src\bind.cc) [...\node_modules\krb5\build\krb5.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `...\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (...\nvm\v6.9.1\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "...\\nodejs\\node.exe" "...\\nvm\\v6.9.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd ...\node_modules\krb5
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: krb5@0.1.0 (node_modules\krb5):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: krb5@0.1.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

**Comment by Lutziferbox** [comment]
The same happens on the linux build machine:

> krb5@0.1.0 install .../node_modules/krb5
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@6.2.1 | linux | x64
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (.../node_modules/npm/node_modules/node-gyp/lib/configure.js:401:14)
gyp ERR! stack     at .../node_modules/npm/node_modules/node-gyp/lib/configure.js:330:11
gyp ERR! stack     at F (.../node_modules/npm/node_modules/which/which.js:69:16)
gyp ERR! stack     at E (.../node_modules/npm/node_modules/which/which.js:81:29)
gyp ERR! stack     at .../node_modules/npm/node_modules/which/which.js:90:16
gyp ERR! stack     at .../node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at .../node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:117:15)
gyp ERR! System Linux 3.10.0-514.6.1.el7.x86_64
gyp ERR! command ".../node" ".../node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd .../node_modules/krb5
gyp ERR! node -v v6.2.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 


> krb5@0.1.0 install .../node_modules/krb5
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (.../node_modules/npm/node_modules/node-gyp/lib/configure.js:449:14)
gyp ERR! stack     at .../node_modules/npm/node_modules/node-gyp/lib/configure.js:353:11
gyp ERR! stack     at F (.../node_modules/npm/node_modules/which/which.js:69:16)
gyp ERR! stack     at E (.../node_modules/npm/node_modules/which/which.js:81:29)
gyp ERR! stack     at .../node_modules/npm/node_modules/which/which.js:90:16
gyp ERR! stack     at .../node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at .../node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Linux 3.10.0-514.6.1.el7.x86_64
gyp ERR! command ".../node" ".../node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd .../node_modules/krb5
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: krb5@0.1.0 (node_modules/krb5):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: krb5@0.1.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
